package com.github.kyungmin08g.zephyro.query.enums;

import lombok.Getter;

@Getter
public enum SQLKeyword {
  SELECT, FROM, WHERE, GROUP, HAVING, ORDER, INSERT, INTO,
  VALUES, UPDATE, SET, DELETE, JOIN, LEFT, RIGHT, FULL,
  UNION, ALL, SUBQUERY, EXISTS, NOT, ANY, LIKE, BETWEEN,
  IN, DESC, ASC, BY, COUNT, MAX, MIN, AVG, SUM, LENGTH,
  UPPER, LOWER, INITCAP, TRIM, REPLACE, CONCAT, SYSDATE, NVL, COALESCE,
  ROWNUM, DECODE, CASE, ROWID, GRANT, REVOKE, CREATE, ALTER,
  DROP, TABLE, INDEX, VIEW, COMMIT, ROLLBACK, SAVEPOINT, TO,
  TRANSACTION, SYNONYM, SEQUENCE, NEXTVAL, CURRVAL, TRUNCATE,
  OUTER, CROSS, DISTINCT, EXCEPT, INNER, INTERSECT, LIMIT,
  MINUS, CALL, NULL, OR, AND, IS
}
